# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://pesati.github.io/
title: André Pesati Revoredo
email: pesatirevoredo@gmail.com
author: André Pesati Revoredo
description: "Andre Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/Pesati 
  - icon: envelope-o
    title: email
    url: mailto:pesatirevoredo@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/andrepesati/
  - icon: file-pdf-o
    title: CV
    url: img/AndreCV.pdf
#  - icon: website
#    title: CV Lattes
#    url: http://lattes.cnpq.br/5399100590606067



